/** Opaque identifier generated by the Supplier Service. */
export type SupplierId = string & { readonly __brand: 'SupplierId' }

export type Day = 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday'

/** Service categories accepted by the supplier requirements. */
export type ServiceType = 'printing' | 'pick-ups' | 'product-purchasing' | 'food-and-beverage'

export type OperatingHours = {
  /** 24-hour time in HH:mm format. */
  openingTime: string
  /** 24-hour time in HH:mm format. */
  closingTime: string
  daysOfWeek: Day[]
}

export type Location = {
  lat: number
  lng: number
  buildingName: string
  floorNum: number
}

/** Supplier record returned by the Supplier Service. */
export type Supplier = {
  readonly id: SupplierId
  name: string
  location: Location
  isOperational: boolean
  operatingHours: OperatingHours
  serviceTypes: ServiceType[]
}
