server {
  listen 80;
  root /usr/share/nginx/html;

  location = /api/supplier {
    proxy_pass http://supplier-api:3000/api/supplier;
    proxy_set_header Host $host;
  }

  location /api/supplier/ {
    proxy_pass http://supplier-api:3000/api/supplier/;
    proxy_set_header Host $host;
  }

  location = /healthz { default_type text/plain; return 200 "ok\n"; }
  location / { try_files $uri $uri/ /index.html; }
}
